name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    name: Tests
    timeout-minutes: 5
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.15

      - uses: actions/checkout@v2

      - name: Get dependencies
        run: go mod download

      - name: Unit tests
        run: make test

      - uses: codecov/codecov-action@v1
        with:
          file: .test_coverage.txt
          flags: unittests
          verbose: true

  linters:
    name: Linters
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: golangci/golangci-lint-action@v2
        with:
          version: v1.33
          args: --timeout=5m
